### ISSUE TITLE
Mutiple scratch card can't be having same source of image

### ISSUE THREAD

**Issue by prajeesh-splendre** [sweatco/rn-scratch-card#2]
Once the scratch is completed in a component, every other scratch card with the same source of image is showing like scratched, this is not getting resetted even after unmounting the component.

Also another issue 

the image shown in the masonry list is not a scratch card but the same source of image used, it is getting scratched too 

![image](https://user-images.githubusercontent.com/86819567/159874458-071d7d1e-6301-4569-9edd-a8ddd50544f1.png)

**Comment by avegrv** [comment]
@prajeesh-splendre Fixed. Please update up to **1.0.0-beta7**
