### ISSUE TITLE
Prop for Images from URL

### ISSUE THREAD

**Issue by kloehz** [sweatco/rn-scratch-card#6]
Hello!

Thanks for the library <3

im here with a question...can you implement a prop that accept an url for the image? this is because now im fetching the image from backend with react-native-fs, saving it on temp directory, get this file and parse it to base64 to show them.

i mean its a nice feature but i don know how to code them in swift/kotlin to implement it (i try on swift, if i can do it, i write the code on a pr)

Thanks you!

**Comment by avegrv** [comment]
@kloehz Thank you that you choose our lib.

The lib uses the same props as [Image](https://reactnative.dev/docs/image) class from react-native.
Basic on the [stackoverflow](https://stackoverflow.com/questions/56264942/how-to-render-images-with-react-native-fs) question, I guess you can try something similar:

```
const RNFS = require('react-native-fs') // https://github.com/itinance/react-native-fs#readme (npm install react-native-fs)
const platformFilePath = Platform.OS === 'android' ? RNFS.DocumentDirectoryPath : RNFS.MainBundlePath;
const filePath = "file://" + platformFilePath + "/" + this.props.imageName

return(
   <ScratchCard source={{uri:filePath}} style={...} /> 
)
```
