### ISSUE TITLE
how to apply To expo project

### ISSUE THREAD

**Issue by markjornales** [sweatco/rn-scratch-card#8]

**Comment by avegrv** [comment]
Hey @markjornales , the lib doesn't support the expo.
Anyway, you can try implementing the scratch functionality based on react-native-skia like [here](https://github.com/Augustach/scratch-card-skia).
Regarding [documentation](https://shopify.github.io/react-native-skia/docs/getting-started/web/), react-native-skia can be used inside expo.

**Comment by markjornales** [comment]
> Hey @markjornales , the lib doesn't support the expo. Anyway, you can try implementing the scratch functionality based on react-native-skia like [here](https://github.com/Augustach/scratch-card-skia). Regarding [documentation](https://shopify.github.io/react-native-skia/docs/getting-started/web/), react-native-skia can be used inside expo.

thank you
